[project]
name = "genai-journey"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sujit kolli", email = "kolli.sujit@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2.14.0",
    "python-dotenv>=1.2.4",
    "requests>=2.34.2",
]

[project.scripts]
genai-journey = "genai_journey:main"

[build-system]
requires = ["uv_build>=0.12.24,<0.13.0"]
build-backend = "uv_build"
